project:
  type: website
  output-dir: docs

website:
  title: "Conecta Stat"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - href: people.qmd
        text: Pessoas
      - href: projects.qmd
        text: Projetos
      - href: events.qmd
        text: Eventos
      - href: contact.qmd
        text: Contato
  page-footer:
    left: |
      **Conecta Stat**  
      Hub de Inovação em Estatística
      
      Departamento de Estatística  
      Universidade Federal de Lavras - UFLA
      
      [![Email](https://img.shields.io/badge/Email-conecta.stat.ufla@gmail.com-f7fafc?style=for-the-badge&logo=gmail&logoColor=4a5568&color=f7fafc&labelColor=f7fafc)](mailto:conecta.stat.ufla@gmail.com)
      [![GitHub](https://img.shields.io/badge/GitHub-conecta--stat-f7fafc?style=for-the-badge&logo=github&logoColor=4a5568&color=f7fafc&labelColor=f7fafc)](https://github.com/conecta-stat)
    right: |
      Desenvolvido com [Quarto](https://quarto.org/){target="_blank"}  
      © 2025 UFLA

format:
  html:
    theme: cosmo
    css: styles.css
    link-external-newwindow: true
    include-in-header:
      - text: |
          <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.4.0/css/all.min.css">



