project:
  type: website
  output-dir: docs

website:
  title: "Conecta Stat"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - href: people.qmd
        text: Pessoas
      - href: projects.qmd
        text: Projetos
      - href: events.qmd
        text: Eventos
      - href: contact.qmd
        text: Contato
  page-footer:
    left: "© 2024 Departamento de Estatística"
    right: "Desenvolvido com [Quarto](https://quarto.org/)"

format:
  html:
    theme: cosmo
    css: styles.css
    link-external-newwindow: true
    include-in-header:
      - text: |
          <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.4.0/css/all.min.css">



